//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//
//     このファイルへの変更は、正しくない動作の原因となる場合があります。
//     コードが再生成されます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormApplication {


    public partial class HelloWorld {
        
        /// <summary>
        /// LabelMessage コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelMessage;
        
        /// <summary>
        /// TextBoxName コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBoxName;
        
        /// <summary>
        /// ButtonGreet コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonGreet;
    }
}
